export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PERSISTENT_DATA = 'GET_PERSISTENT_DATA';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';